name: Demo

# Trigger the workflow on a schedule and manually
on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2 AM UTC
  workflow_dispatch: # Allows manual triggering
    inputs:
      hello:
        description: "Hello"
        required: true
        default: "world"

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ${{ github.workspace }}
      HELLO: ${{ github.event.inputs.hello }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Demo Script
        run: pwsh ./_demo/run.ps1
        shell: pwsh

